services:
  web:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - dash_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_U}
      POSTGRES_PASSWORD: ${PG_P}
      POSTGRES_DB: dash
    ports:
      - '5432:5432'

volumes:
  dash_db:
  node_modules: